spring:
  application:
    name: aobihelper-backend
  config:
    import:
      - optional:file:./config/mail-local.yml
      - optional:file:./backend/config/mail-local.yml
  profiles:
    active: dev

server:
  port: 8080
  servlet:
    context-path: /

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
